### ISSUE TITLE
Will the r-pfbwt index compatible with existing short read aligner?

### ISSUE THREAD

**Issue by RunpengLuo** [marco-oliva/r-pfbwt#9]
Dear Developers,

Many thanks for developing this fast pan genome index software `r-pfbwt`. I want to try this method but just have some quick questions. Apologise in advance if the question is immature.

In general I would like to build a pan genome index and fed it to BWA to do short read alignment. I will be using multiple human references. I found that [Big-BWT](https://github.com/alshai/Big-BWT) explicitly mentioned that they would output index file in `.bwt` format, which I guess it   would be compatible with existing BWT-type aligners such as BWA. I notice that  `r-pfbwt` will output `.rlbwt` format index. Will it compatible with aligner such as BWA? Otherwise, is there any NGS aligners for recommendation that can use such index.

Thanks again and looking forward to your reply!

Best Regards,
Runpeng

**Comment by marco-oliva** [comment]
Hi Runpeng, 

thank you for reaching out. This repository is deprecated, please post the issue here: https://github.com/EddieFerro/rPFP.

Best,
Marco.
